//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by PanoDemo.rc
//
#define IDPANE_STATUS                   1
#define IDPANE_VIEW                     2
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDD_MAINDLG                     129
#define IDR_TOOLBAR_WB                  203
#define IDR_TOOLBAR_HOLLOW              207
#define IDR_TOOLBAR1                    212
#define IDR_TOOLBAR_MEDIA               212
#define IDR_TOOLBAR_COLOR               213
#define IDR_MENU_COLOR                  214
#define IDR_TOOLBAR_STAMP               214
#define IDR_MENU_HOLLOW                 215
#define IDR_TOOLBAR_ERASER              215
#define IDR_MENU_STAMP                  216
#define IDR_MENU_MEDIA                  217
#define IDR_MENU_ERASER                 218
#define IDC_START_CALL                  1000
#define IDC_BTN_CAMERA_PREVIEW          1001
#define IDC_EDIT_CHANNEL_ID             1002
#define IDC_EDIT_USER_ID                1003
#define IDC_EDIT_APPID                  1004
#define IDC_EDIT_USER_NAME              1005
#define IDC_BTN_CHANNEL_INFO            1006
#define IDC_EDIT_YUV_FILE               1006
#define IDC_COMBO_CAMERA                1007
#define IDC_COMBO_RESOLUTION            1008
#define IDC_COMBO_MICROPHONE            1009
#define IDC_COMBO_SPEAKER               1010
#define IDC_EDIT_RTC_SERVER             1011
#define IDC_EDIT_AUTH_SIGN              1012
#define IDC_COMBO_SHARING               1012
#define IDC_COMBO_SOURCE                1012
#define IDC_CHECK1                      1013
#define IDC_CHECK_CHAN_MODE             1013
#define IDC_COMBO_SCALING_MODE          1014
#define IDC_CHECK_CHAN_MODE2            1015
#define IDC_CHECK_MIRROR                1015
#define IDC_CHECK2                      1016
#define IDC_CHECK_HW_ACCELERATION       1016
#define IDC_CHECK_CHAN_MODE3            1016
#define IDC_EDIT_RTC_SERVER2            1017
#define IDC_EDIT_APP_SERVER             1017
#define IDC_BTN_AUDIO_MUTE              1018
#define IDC_BTN_SHARE_START             1019
#define IDC_BTN_VIDEO_MUTE              1020
#define IDC_BTN_SHARE_PAUSE             1021
#define IDC_BTN_SHARE_MUTE              1021
#define IDC_CHECK_ENABLE_VIDEO          1022
#define IDC_CHECK_ENABLE_VIDEO2         1023
#define IDC_CHECK_ENABLE_AUDIO          1023
#define IDC_CHECK_SHARE_MOTION          1024
#define IDC_CHECK_ENABLE_WHITEBOARD     1025
#define IDC_CHECK_RECORD_AUDIO          1026
#define IDC_COMBO_EQUALIZATION          1026
#define IDC_BTN_VIDEO_MUTE2             1026
#define IDC_BTN_YUV_BROWSE              1026
#define IDC_CHECK_RECORD_VIDEO          1027
#define IDC_COMBO_REVERB                1027
#define IDC_CHECK_RECORD_SHARING        1028
#define IDC_CHECK_ENABLE_VIDEO3         1028
#define IDC_CHECK_VIDEO_LOW_FPS         1028
#define IDC_CHECK_RECORD_WHITEBOARD     1029
#define IDC_COMBO_RECORD_TYPE           1030
#define IDC_EDIT1                       1031
#define IDC_EDIT_RECORD_LAYOUT          1031
#define IDC_CHECK_CHAN_UPLOAD_LOGS      1032
#define IDC_BTN_AUDIO_DUMP              1033
#define IDC_CHECK_AUDIO_UPLOAD_DUMP     1034
#define IDC_BTN_AUDIO_DUMP2             1035
#define IDC_BTN_AUDIO_TEST              1035
#define IDC_BUTTON_AUDIO_MIXING         1036
#define IDC_STATIC18                    1038
#define IDC_BTN_SNAPSHOT                1039
#define IDM_WB_SELECT                   32775
#define IDM_WB_PEN                      32776
#define IDM_WB_ERASER                   32777
#define IDM_WB_TEXT                     32778
#define IDM_WB_RECTANGLE                32780
#define IDM_WB_LINE                     32781
#define IDM_WB_ELLIPSE                  32784
#define IDM_WB_UNDO                     32785
#define IDM_WB_REDO                     32786
#define IDM_WB_FORE_COLOR               32787
#define IDM_WB_BOLD                     32788
#define IDM_WB_ITALIC                   32789
#define IDM_WB_FONT                     32795
#define IDM_WB_LINE_WIDTH               32796
#define IDM_WB_BRUSH                    32797
#define IDM_WB_ARROW                    32799
#define IDM_WB_ARC                      32800
#define IDM_WB_CURVE                    32801
#define IDM_WB_POLYLINE                 32803
#define IDM_WB_POLYGON                  32805
#define IDM_WB_SNAPSHOT                 32806
#define IDM_PREV_PAGE                   32807
#define IDM_ADD_PAGE                    32808
#define IDM_DEL_PAGE                    32809
#define IDM_NEXT_PAGE                   32810
#define IDM_WB_IMAGE                    32811
#define IDM_WB_DOC                      32812
#define IDM_WB_DOC_LIST                 32813
#define IDM_ZOOMIN                      32814
#define IDM_ZOOMOUT                     32815
#define IDM_WB_PLAY                     32816
#define IDM_WB_LASER                    32817
#define IDM_WB_VIDEO                    32818
#define IDM_WB_AUDIO                    32819
#define IDM_ADMIN                       32820
#define IDM_WB_HOLLOW                   32825
#define IDM_WB_STAMP_CROSS              32830
#define IDM_WB_STAMP_PRAISE             32833
#define IDM_WB_STAMP                    32835
#define IDM_WB_COLOR_BLACK              32836
#define IDM_WB_COLOR_RED                32837
#define IDM_WB_COLOR_GREEN              32838
#define IDM_WB_COLOR_BLUE               32839
#define IDM_WB_COLOR_YELLOW             32840
#define IDM_WB_STAMP_HEART              32841
#define IDM_WB_STAMP_TICK               32842
#define IDM_WB_STAMP_STAR               32843
#define IDM_WB_MEDIA                    32845
#define ID_MEDIA_IMAGE                  32846
#define IDM_WB_BACKGROUND               32847
#define IDM_WB_IMAGE_BACKGROUND         32848
#define IDM_WB_ERASE                    32850
#define IDM_WB_ERASER_ONE               32851
#define IDM_WB_CLEAR                    32852
#define IDM_WB_ERASER_BRUSH             32853
#define IDM_WB_ERASER_CLEAR             32854
#define IDM_WB_STAMP_HOUSE              32855
#define IDM_WB_STAMP_ROCKET             32856

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        219
#define _APS_NEXT_COMMAND_VALUE         32857
#define _APS_NEXT_CONTROL_VALUE         1040
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
